language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sbalasani/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run sbalasani/react-test npm test -- --coverage

script:
  - docker run -e CI=true sbalasani/react-test npm run test -- --coverage

after_success:
  - docker build -t sbalasani/multi-client ./client
  - docker build -t sbalasani/multi-nginx ./nginx
  - docker build -t sbalasani/multi-server ./server
  - docker build -t sbalasani/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sbalasani/multi-client
  - docker push sbalasani/multi-nginx
  - docker push sbalasani/multi-server
  - docker push sbalasani/multi-worker

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY